In [1]:
import pandas as pd
from pathlib import Path

In [6]:
PATH = Path(r'C:\Users\82105\kamp_ai_competition\dataset')

scaled_data = pd.read_csv(PATH / 'scaled_data.csv', encoding='cp949')
raw_data = pd.read_excel(PATH / 'Welding Data Set_01.xlsx', sheet_name=0)
result = pd.read_excel(PATH / 'Welding Data Set_01.xlsx', sheet_name=1)
data_info = pd.read_excel(PATH / 'Welding Data Set_01.xlsx', sheet_name=2)

scaled_data.head()

   Unnamed: 0    용접 가압력        전류        전압      통전시간
0           0  0.004482  0.001717  0.002506  0.000461
1           1  0.005412  0.000501  0.002506  0.000922
2           2  0.004989  0.000358  0.507830  0.000922
3           3  0.005243  0.000358  0.002506  0.000922
4           4  0.005327  0.000143  0.002506  0.000461

In [7]:
raw_data.head()

,idx,Machine_Name,Item No,working time,Thickness 1(mm),Thickness 2(mm),weld force(bar),weld current(kA),weld Voltage(v),weld time(ms)
0,1,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.33,14.57,2.701,72.0
1,2,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.36,14.57,2.701,72.0
2,3,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.37,14.54,2.703,71.0
3,4,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.37,14.54,2.703,72.0
4,5,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.36,14.56,2.704,72.0

In [8]:
result.head()

   idx Machine_Name      Item No working time  defect  defect type Unnamed: 6
0    1      Spot-01  65235-25800   2020-03-24       2            1       파임불량
1    2      Spot-01  65235-25800   2020-03-24       1            2       용접부족
2    3      Spot-01  65235-25800   2020-03-24       1            3       크랙발생
3    4      Spot-01  65235-25800   2020-03-25       3            1        NaN
4    5      Spot-01  65235-25800   2020-03-25       2            2        NaN

In [9]:
data_info.head(10)

               Data    항목 설명        수집 범위
0               idx     생산순번            -
1      Machine_Name     생산설비            -
2           Item No     생산품목            -
3      working time     작업시간            -
4   Thickness 1(mm)  소재 두께 1      0.3-2.3
5   Thickness 2(mm)  소재 두께 2      0.3-2.3
6   weld force(bar)   용접 가압력   1.00~12.00
7  weld current(kA)      전류   12.00~18.00
8   weld Voltage(v)       전압    1.50~3.50
9     weld time(ms)     통전시간       30~120