In [17]:
from sklearn.ensemble import IsolationForest
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd

In [2]:
from data_load import scaled_data, raw_data, result, data_info

In [3]:
scaled_data.head()

   Unnamed: 0    용접 가압력        전류        전압      통전시간
0           0  0.004482  0.001717  0.002506  0.000461
1           1  0.005412  0.000501  0.002506  0.000922
2           2  0.004989  0.000358  0.507830  0.000922
3           3  0.005243  0.000358  0.002506  0.000922
4           4  0.005327  0.000143  0.002506  0.000461

In [4]:
raw_data.head()

,idx,Machine_Name,Item No,working time,Thickness 1(mm),Thickness 2(mm),weld force(bar),weld current(kA),weld Voltage(v),weld time(ms)
0,1,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.33,14.57,2.701,72.0
1,2,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.36,14.57,2.701,72.0
2,3,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.37,14.54,2.703,71.0
3,4,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.37,14.54,2.703,72.0
4,5,Spot-01,65235-25800,2020-03-24,0.7,0.7,2.36,14.56,2.704,72.0

In [ ]:
# Thickness는 모두 같은 값이므로 예측에 영향 X

print(np.sum(raw_data['Thickness 1(mm)'] != 0.7))
print(np.sum(raw_data['Thickness 2(mm)'] != 0.7))

0
0

In [12]:
scaled_data = scaled_data.drop(columns = ['Unnamed: 0'])

In [28]:
model = IsolationForest(contamination=0.1, random_state=42)

model.fit(scaled_data)

predictions = model.predict(scaled_data)

idx = (predictions == -1)

X = scaled_data.loc[idx, :]

In [29]:
X_clean = X.dropna()

kmeans = KMeans(n_clusters=3, n_init='auto', random_state=42)

kmeans.fit(X_clean)

labels = kmeans.labels_
print("각 데이터의 소속 그룹:", labels)
print(type(labels))

각 데이터의 소속 그룹: [0 0 1 ... 2 2 0]
<class 'numpy.ndarray'>

In [33]:
pred = pd.concat(
    [X_clean, pd.DataFrame(labels)], axis = 1
)

pred.head(30)

        용접 가압력        전류        전압      통전시간    0
2     0.004989  0.000358  0.507830  0.000922  1.0
9     0.004989  0.000072  0.508875  0.000000  0.0
16    0.414849  0.000501  0.002506  0.000461  1.0
25    0.467275  0.000429  0.002506  0.000461  2.0
26    0.005412  0.000429  0.608060  0.000461  2.0
33    0.005243  0.289598  0.002610  0.000922  0.0
47    1.000000  0.000572  0.002610  0.000922  0.0
55    0.940808  0.000501  0.002506  0.000922  0.0
59    0.005327  0.325368  0.002401  0.000461  0.0
81    0.005327  0.384747  0.002610  0.000461  0.0
94    0.005158  0.532837  0.002610  0.000922  0.0
145   0.414849  0.000000  0.002610  0.001382  0.0
146   0.414849  0.000000  0.002610  0.000922  0.0
426   0.005158  0.001073  0.002506  0.705991  0.0
427   0.005158  0.001073  0.002506  0.705991  0.0
490   0.415187  0.001645  0.002506  0.000922  0.0
491   0.415187  0.001645  0.002506  0.000461  0.0
494   0.499746  0.001645  0.002506  0.000461  0.0
495   0.536952  0.001645  0.002506  0.000922  0.0
584   0.004820  0.291100  0.002506  0.000461  1.0
986   0.492728  0.001717  0.002610  0.000922  0.0
1130  0.004735  0.001431  0.002506  0.487097  0.0
1131  0.004735  0.001431  0.002506  0.625346  0.0
1510  0.004735  0.001431  0.002506  0.487097  NaN
1511  0.004735  0.001431  0.002506  0.487097  NaN
1534  0.004735  0.001431  0.002506  0.487097  NaN
1689  0.004820  0.002075  0.002506  0.566820  NaN
1692  0.004989  0.369008  0.002610  0.000922  NaN
1693  0.004989  0.512448  0.002610  0.000922  NaN
1750  0.003974  0.001359  0.002401  0.000000  NaN